-- AcreSync M0 :: 0003 :: Domain 2, identity layer
--
-- This is the only place in the system where personal data exists in a
-- recoverable form. Everything downstream, on-chain or pinned to IPFS, refers to
-- an investor through investor_anchors.anchor_hash and nothing else.


-- ---------------------------------------------------------------------------
-- investors
-- ---------------------------------------------------------------------------

CREATE TABLE investors (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Application-layer envelope-encrypted ciphertext. The orchestrator encrypts
    -- with a data key wrapped by a KMS master key, so Postgres holds neither
    -- plaintext nor any key material. pgcrypto is deliberately not used for
    -- this: a database-side encryption function puts the key in the query, which
    -- puts it in the statement log.
    full_name_enc   BYTEA       NOT NULL,
    pan_enc         BYTEA       NOT NULL,
    email_enc       BYTEA       NOT NULL,
    phone_enc       BYTEA       NOT NULL,
    address_enc     BYTEA,
    dob             DATE,

    investor_class  investor_class NOT NULL,

    -- Investment manager, its related parties and associates are excluded from
    -- the 200-unitholder count.
    is_im_related   BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Synthetic investors generated by the demo bid seeder. Flagged so that a
    -- simulated holder can never be mistaken for a real one, and so that the
    -- anchor pepper can be scoped separately.
    is_synthetic    BOOLEAN     NOT NULL DEFAULT FALSE,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT investors_enc_nonempty CHECK (
        octet_length(full_name_enc) > 0
        AND octet_length(pan_enc)   > 0
        AND octet_length(email_enc) > 0
        AND octet_length(phone_enc) > 0
    )
);

-- ---------------------------------------------------------------------------
-- investor_anchors
-- ---------------------------------------------------------------------------

-- The bridge between the identified world and the pseudonymous one.
--
-- anchor_hash = HMAC-SHA256(pepper, internal_investor_uuid || scheme_ref)
--
-- Two deliberate properties:
--
--   The HMAC input is the internal UUID, never the PAN. A PAN is format
--   constrained to roughly 2.6 billion possibilities and a plain keccak of one is
--   recoverable by enumeration in minutes. A v4 UUID is not.
--
--   The pepper lives in a KMS, not here. Destroying that key severs every
--   linkage between on-chain anchors and identified investors simultaneously,
--   which is the only mechanism by which a DPDP erasure request can be honoured
--   against data already anchored to an immutable ledger. That is what
--   shredded_at records.
CREATE TABLE investor_anchors (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    investor_id   UUID        NOT NULL UNIQUE REFERENCES investors(id) ON DELETE RESTRICT,
    scheme_id     UUID        NOT NULL REFERENCES schemes(id) ON DELETE RESTRICT,
    anchor_hash   BYTEA       NOT NULL,
    pepper_key_id TEXT        NOT NULL,
    algo_version  INTEGER     NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    shredded_at   TIMESTAMPTZ,

    CONSTRAINT investor_anchors_hash_len CHECK (octet_length(anchor_hash) = 32),
    CONSTRAINT investor_anchors_algo_pos CHECK (algo_version >= 1),

    -- A collision here would silently merge two investors' holdings.
    UNIQUE (scheme_id, anchor_hash)
);

-- ---------------------------------------------------------------------------
-- wallets
-- ---------------------------------------------------------------------------

CREATE TABLE wallets (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    investor_id       UUID        NOT NULL REFERENCES investors(id) ON DELETE RESTRICT,
    address           TEXT        NOT NULL UNIQUE,
    provider          wallet_provider NOT NULL DEFAULT 'WEB3AUTH',
    is_active         BOOLEAN     NOT NULL DEFAULT TRUE,
    activated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deactivated_at    TIMESTAMPTZ,
    rotation_reason   TEXT,

    CONSTRAINT wallets_address_fmt CHECK (address ~ '^0x[0-9a-f]{40}$'),
    CONSTRAINT wallets_deactivation_consistent CHECK (
        (is_active AND deactivated_at IS NULL) OR (NOT is_active AND deactivated_at IS NOT NULL)
    )
);

-- Wallet rotation is supported (many wallets per investor over time) but exactly
-- one may be active. The holding is keyed to the investor, not the wallet, so a
-- rotation does not orphan a balance.
CREATE UNIQUE INDEX wallets_one_active_per_investor
    ON wallets(investor_id) WHERE is_active;

-- ---------------------------------------------------------------------------
-- kyc_records
-- ---------------------------------------------------------------------------

CREATE TABLE kyc_records (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    investor_id  UUID        NOT NULL REFERENCES investors(id) ON DELETE RESTRICT,
    provider     TEXT        NOT NULL,
    kyc_ref      TEXT        NOT NULL,
    status       kyc_status  NOT NULL DEFAULT 'PENDING',
    verified_at  TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    country_code SMALLINT    NOT NULL DEFAULT 356,
    is_pep       BOOLEAN     NOT NULL DEFAULT FALSE,
    risk_band    TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT kyc_verified_has_timestamp CHECK (
        status <> 'VERIFIED' OR (verified_at IS NOT NULL AND expires_at IS NOT NULL)
    ),
    CONSTRAINT kyc_expiry_after_verification CHECK (
        expires_at IS NULL OR verified_at IS NULL OR expires_at > verified_at
    )
);

CREATE INDEX kyc_records_investor_idx ON kyc_records(investor_id);

-- ---------------------------------------------------------------------------
-- demat_accounts
-- ---------------------------------------------------------------------------

-- The depository is the legal registry of unit ownership. In v1 it is simulated,
-- but the schema is shaped for the real thing so that swapping the simulator for
-- a CDSL or NSDL adapter does not require a migration.
CREATE TABLE demat_accounts (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    investor_id  UUID        NOT NULL REFERENCES investors(id) ON DELETE RESTRICT,
    depository   depository  NOT NULL,
    dp_id        TEXT        NOT NULL,
    client_id    TEXT        NOT NULL,
    is_primary   BOOLEAN     NOT NULL DEFAULT TRUE,
    verified_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (depository, dp_id, client_id)
);

CREATE UNIQUE INDEX demat_one_primary_per_investor
    ON demat_accounts(investor_id) WHERE is_primary;

-- ---------------------------------------------------------------------------
-- bank_accounts
-- ---------------------------------------------------------------------------

CREATE TABLE bank_accounts (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    investor_id           UUID        NOT NULL REFERENCES investors(id) ON DELETE RESTRICT,
    account_number_enc    BYTEA       NOT NULL,
    ifsc                  TEXT        NOT NULL,
    account_name_enc      BYTEA       NOT NULL,
    asba_enabled          BOOLEAN     NOT NULL DEFAULT TRUE,
    verified_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT bank_accounts_ifsc_fmt CHECK (ifsc ~ '^[A-Z]{4}0[A-Z0-9]{6}$'),
    CONSTRAINT bank_accounts_enc_nonempty CHECK (
        octet_length(account_number_enc) > 0 AND octet_length(account_name_enc) > 0
    )
);

CREATE INDEX bank_accounts_investor_idx ON bank_accounts(investor_id);

