// Package bidbook freezes a validated set of bids into the document the draw is bound to.
//
// # What freezing actually means
//
// The bid book root is anchored on-chain before the seed is committed, and the root feeds the seed. So
// the book is the one artefact in the primary market that cannot move afterwards: a later edit produces
// a different root, a different seed, and a visibly different draw. Everything the ballot's fairness
// claim rests on starts here.
//
// That puts two requirements on this package. The leaf ordering has to be a function of the data rather
// than of whatever order a database returned, or the same set of bids would produce different roots on
// different runs. And every bid admitted has to be genuinely funded, because a bid in the book without
// money behind it can win units it cannot pay for, and the shortfall surfaces at debit time with the cap
// table already anchored.
package bidbook

import (
	"errors"
	"fmt"
	"math"
	"sort"
	"time"

	"github.com/acresync/orchestrator/internal/asba"
	"github.com/acresync/orchestrator/internal/ballot"
	"github.com/acresync/orchestrator/internal/merkle"
	"github.com/acresync/orchestrator/internal/money"
)

var (
	ErrEmptyBook         = errors.New("bidbook: no bids to freeze")
	ErrDuplicateInvestor = errors.New("bidbook: two bids from one investor")
	ErrDuplicateBidRef   = errors.New("bidbook: two bids share a reference")
	ErrDuplicateAnchor   = errors.New("bidbook: two bids share an investor anchor")
	ErrUnfunded          = errors.New("bidbook: bid is not backed by a confirmed funds block")
	ErrAmountMismatch    = errors.New("bidbook: blocked amount does not match the bid")
	ErrTotalOverflow     = errors.New("bidbook: total units bid exceeds what the document can express")
	ErrCountsDisagree    = errors.New("bidbook: leaf count and distinct bidder count disagree")
)

// Entry is one validated bid, with the funds block that backs it.
type Entry struct {
	// BidID and InvestorID are internal identifiers. Neither is published.
	BidID      string
	InvestorID string

	// BidRef is the investor's application reference: 32 lowercase hex characters, 16 bytes.
	//
	// Generated by AcreSync rather than supplied by the investor, and it is the identifier they are
	// given as a receipt. That matters for how the book is ordered; see assignLeafIndices.
	BidRef string

	// InvestorAnchor is the HMAC anchor. Published in place of any identifying detail.
	InvestorAnchor merkle.Hash

	UnitsBid          uint32
	PricePerUnitPaise money.Paise

	// Block is the ASBA reservation backing this bid.
	//
	// Carried rather than looked up, so freezing is a pure function of what it was handed and can be
	// tested against a funded book and an underfunded one without a database.
	Block *asba.Block
}

// TotalPaise is the amount this bid commits to.
func (e Entry) TotalPaise() (money.Paise, error) {
	if e.UnitsBid == 0 {
		return 0, fmt.Errorf("bidbook: bid %s is for zero units", e.BidID)
	}
	total := money.Paise(int64(e.UnitsBid)) * e.PricePerUnitPaise
	if e.PricePerUnitPaise != 0 && total/e.PricePerUnitPaise != money.Paise(int64(e.UnitsBid)) {
		return 0, fmt.Errorf("bidbook: bid %s total overflowed", e.BidID)
	}
	return total, nil
}

// Line is a frozen book entry with its assigned position and leaf.
type Line struct {
	Entry

	LeafIndex uint32
	Leaf      merkle.Hash
}

// Book is a frozen bid book.
type Book struct {
	// SchemeRef is the 32-byte on-chain scheme reference, published in the document.
	SchemeRef merkle.Hash

	// SchemeID is the internal scheme UUID. Not published; used for idempotency scoping.
	//
	// Distinct from SchemeRef on purpose. One is the public identifier the contract knows, the other is
	// a database key, and conflating them would put a database key in a pinned document.
	SchemeID string

	OfferID  string
	FrozenAt time.Time

	// Lines are ordered by ascending leaf index, which is the order the root was built in.
	Lines []Line

	MerkleRoot merkle.Hash

	LeafCount       uint32
	TotalUnitsBid   uint32
	DistinctBidders uint32

	// TotalAmountPaise is the sum of every bid's commitment, and equals the total blocked.
	TotalAmountPaise money.Paise

	AlgoVersion uint32

	byBidRef map[string]uint32
	tree     *merkle.Tree
}

// FreezeInput is everything needed to fix a book.
type FreezeInput struct {
	SchemeRef merkle.Hash
	SchemeID  string
	OfferID   string

	// FrozenAt is business time, supplied rather than read.
	FrozenAt time.Time

	Entries []Entry
}

// Freeze fixes the book, assigns leaf positions and computes the root.
func Freeze(in FreezeInput) (*Book, error) {
	if len(in.Entries) == 0 {
		return nil, ErrEmptyBook
	}

	ordered, err := assignLeafIndices(in.Entries)
	if err != nil {
		return nil, err
	}

	book := &Book{
		SchemeRef:   in.SchemeRef,
		SchemeID:    in.SchemeID,
		OfferID:     in.OfferID,
		FrozenAt:    in.FrozenAt,
		Lines:       make([]Line, 0, len(ordered)),
		AlgoVersion: ballot.AlgoVersion,
		byBidRef:    make(map[string]uint32, len(ordered)),
	}

	bids := make([]ballot.Bid, 0, len(ordered))
	investors := make(map[string]bool, len(ordered))

	var totalUnits uint64

	for i, e := range ordered {
		idx := uint32(i)

		// Every bid must be funded, and funded for exactly what it bids.
		//
		// The block is checked against units times price rather than merely being present. A block
		// placed before a correction to units or price would still be BLOCKED while covering the wrong
		// amount, and that bid would be admitted to the book underfunded by exactly the difference.
		if e.Block == nil {
			return nil, fmt.Errorf("%w: bid %s has no block", ErrUnfunded, e.BidID)
		}
		if !e.Block.Status.HoldsFunds() {
			return nil, fmt.Errorf("%w: bid %s has a block in state %s",
				ErrUnfunded, e.BidID, e.Block.Status)
		}
		if err := e.Block.Reconcile(); err != nil {
			return nil, fmt.Errorf("bid %s: %w", e.BidID, err)
		}

		want, err := e.TotalPaise()
		if err != nil {
			return nil, err
		}
		if e.Block.BlockedPaise != want {
			return nil, fmt.Errorf("%w: bid %s bids %d units at %d paise, totalling %d, but %d is "+
				"blocked", ErrAmountMismatch, e.BidID, e.UnitsBid, e.PricePerUnitPaise,
				want, e.Block.BlockedPaise)
		}

		if investors[e.InvestorID] {
			// The database enforces one bid per investor per offer. Two would let a single investor
			// circumvent the per-bid cap and count twice toward the holder floor.
			return nil, fmt.Errorf("%w: %s", ErrDuplicateInvestor, e.InvestorID)
		}
		investors[e.InvestorID] = true

		b := ballot.Bid{
			LeafIndex:         idx,
			BidRef:            e.BidRef,
			InvestorAnchor:    e.InvestorAnchor,
			UnitsBid:          e.UnitsBid,
			PricePerUnitPaise: e.PricePerUnitPaise,
		}

		leaf, err := ballot.BidLeaf(b)
		if err != nil {
			return nil, fmt.Errorf("bid %s: %w", e.BidID, err)
		}

		book.Lines = append(book.Lines, Line{Entry: e, LeafIndex: idx, Leaf: leaf})
		book.byBidRef[e.BidRef] = idx
		bids = append(bids, b)

		totalUnits += uint64(e.UnitsBid)

		if book.TotalAmountPaise, err = book.TotalAmountPaise.Add(want); err != nil {
			return nil, err
		}
	}

	// The document types the total as uint32, so a book that cannot be expressed has to be refused here
	// rather than producing a document that silently truncates. On realistic parameters this is
	// unreachable, which is why it needs saying: 900 bids at a 25-unit cap is 22,500.
	if totalUnits > math.MaxUint32 {
		return nil, fmt.Errorf("%w: %d units across %d bids", ErrTotalOverflow, totalUnits, len(ordered))
	}

	book.LeafCount = uint32(len(book.Lines))
	book.TotalUnitsBid = uint32(totalUnits)
	book.DistinctBidders = uint32(len(investors))

	// In v1 these are necessarily equal, because the database permits one bid per investor per offer.
	// A disagreement means either that constraint was bypassed or the book was assembled from the wrong
	// query, and both produce a draw over a population that is not the one the offer received.
	if book.LeafCount != book.DistinctBidders {
		return nil, fmt.Errorf("%w: %d leaves against %d distinct bidders. One bid per investor is "+
			"enforced by the schema, so these cannot legitimately differ",
			ErrCountsDisagree, book.LeafCount, book.DistinctBidders)
	}

	// Delegated rather than reimplemented. The allocation engine owns the leaf encoding and the
	// construction, and it is the version held to the Solidity library by the shared golden vectors.
	root, err := ballot.BidbookRoot(bids)
	if err != nil {
		return nil, fmt.Errorf("bidbook: computing the root: %w", err)
	}
	book.MerkleRoot = root

	// The tree is rebuilt locally so inclusion proofs can be served. Built from the same leaves in the
	// same order, then checked against the engine's root, so a divergence between the two constructions
	// is caught here rather than by an investor whose proof does not verify.
	leaves := make([]merkle.Hash, len(book.Lines))
	for i, l := range book.Lines {
		leaves[i] = l.Leaf
	}
	tree, err := merkle.New(leaves)
	if err != nil {
		return nil, fmt.Errorf("bidbook: building the proof tree: %w", err)
	}
	if tree.Root() != root {
		return nil, fmt.Errorf("bidbook: the proof tree root %s disagrees with the engine's %s",
			tree.Root().Hex(), root.Hex())
	}
	book.tree = tree

	return book, nil
}

// assignLeafIndices imposes a total order on the book.
//
// # Why the order is by bid reference
//
// Leaf index is part of the leaf, so the root depends on the ordering. Whatever order the database
// returned is not a function of the data: a query plan change, a new index, or a re-run after a
// correction would reorder the book and produce a different root for an identical set of bids. Since
// the root feeds the seed, that would change the draw.
//
// The bid reference is the sort key because it is the identifier the investor actually holds. They are
// given it as a receipt when they bid, exactly like an application number, so they can find their own
// leaf in the published document without knowing anything they were not told. The investor anchor is the
// alternative and was rejected for that reason: it is an HMAC under a key in KMS, so an investor cannot
// compute their own, and a document ordered by it would be navigable only by us.
//
// References are generated by AcreSync from a cryptographic source, never supplied by the investor, so
// the position cannot be chosen. Even if it could, position only reaches the draw through the rank key,
// which mixes in a seed that does not exist until after the book is frozen.
func assignLeafIndices(entries []Entry) ([]Entry, error) {
	out := make([]Entry, len(entries))
	copy(out, entries)

	sort.SliceStable(out, func(i, j int) bool { return out[i].BidRef < out[j].BidRef })

	seenRef := make(map[string]string, len(out))
	seenAnchor := make(map[merkle.Hash]string, len(out))

	for _, e := range out {
		if prev, dup := seenRef[e.BidRef]; dup {
			// A duplicate reference would make the sort order ambiguous and the document unnavigable:
			// two investors would look up the same reference and find each other's bids.
			return nil, fmt.Errorf("%w: %s is shared by bids %s and %s",
				ErrDuplicateBidRef, e.BidRef, prev, e.BidID)
		}
		seenRef[e.BidRef] = e.BidID

		if prev, dup := seenAnchor[e.InvestorAnchor]; dup {
			return nil, fmt.Errorf("%w: bids %s and %s", ErrDuplicateAnchor, prev, e.BidID)
		}
		seenAnchor[e.InvestorAnchor] = e.BidID
	}

	return out, nil
}

// Proof returns the inclusion proof for a leaf index.
func (b *Book) Proof(leafIndex uint32) ([]merkle.Hash, error) {
	return b.tree.Proof(int(leafIndex))
}

// ProofForBidRef returns the line and proof for a bid reference.
//
// The lookup an investor performs: they know their reference, not their leaf index.
func (b *Book) ProofForBidRef(ref string) (Line, []merkle.Hash, error) {
	idx, ok := b.byBidRef[ref]
	if !ok {
		return Line{}, nil, fmt.Errorf("bidbook: %s is not in the frozen book", ref)
	}
	proof, err := b.Proof(idx)
	if err != nil {
		return Line{}, nil, err
	}
	return b.Lines[idx], proof, nil
}

// VerifyLine recomputes a line's leaf and checks it against the root.
//
// Recomputed rather than read from the stored Leaf field. Comparing a stored leaf against a root built
// from those same stored leaves proves nothing; recomputing proves the encoding rule and the tree agree,
// which is what an external verifier does.
func (b *Book) VerifyLine(line Line, proof []merkle.Hash) bool {
	leaf, err := ballot.BidLeaf(ballot.Bid{
		LeafIndex:         line.LeafIndex,
		BidRef:            line.BidRef,
		InvestorAnchor:    line.InvestorAnchor,
		UnitsBid:          line.UnitsBid,
		PricePerUnitPaise: line.PricePerUnitPaise,
	})
	if err != nil {
		return false
	}
	return merkle.Verify(b.MerkleRoot, leaf, proof)
}

// BallotBids returns the book in the form the allocation engine consumes.
func (b *Book) BallotBids() []ballot.Bid {
	out := make([]ballot.Bid, 0, len(b.Lines))
	for _, l := range b.Lines {
		out = append(out, ballot.Bid{
			LeafIndex:         l.LeafIndex,
			BidRef:            l.BidRef,
			InvestorAnchor:    l.InvestorAnchor,
			UnitsBid:          l.UnitsBid,
			PricePerUnitPaise: l.PricePerUnitPaise,
		})
	}
	return out
}

// BidIDForLeaf maps a published leaf position back to the internal bid.
//
// Needed when writing allocations, since the engine works in leaf indices and the database works in bid
// identifiers. Kept as a lookup on the book rather than rebuilt at the call site, so the two cannot
// disagree about which bid a leaf belongs to.
func (b *Book) BidIDForLeaf(leafIndex uint32) (string, bool) {
	if leafIndex >= uint32(len(b.Lines)) {
		return "", false
	}
	return b.Lines[leafIndex].BidID, true
}

// OversubscriptionRatio returns demand over supply as an exact fraction.
//
// A fraction rather than a float, because it is published and a rounded ratio invites a reader to
// recompute it and get a different number.
func (b *Book) OversubscriptionRatio(unitsOnOffer uint32) (num uint32, den uint32) {
	return b.TotalUnitsBid, unitsOnOffer
}
