/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a Web3Auth token for an AcreSync session.
         * @description Standard OIDC verification rather than bespoke session handling. The backend validates the
         *     Web3Auth JWT against their JWKS endpoint, maps the subject to an investor, and issues its own
         *     short-lived token. In development the JWKS is a local RSA key pair.
         *
         *     Two identities are deliberately kept apart. Web3Auth establishes *who is calling*; the investor
         *     record establishes *what they hold*. Conflating them would mean a change of login provider
         *     rewrote the register.
         *
         *     Against the mock, any non-empty `idToken` returns a fixed test session.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a direct upload URL for a document.
         * @description Binary content never passes through the API. The client is issued a URL, uploads straight to
         *     storage, and then hands the returned `documentId` to whichever business call needs it.
         *
         *     Keeping blobs out of the request path matters because the pipeline that consumes them anchors
         *     digests on-chain. A multi-megabyte upload sharing a connection with a transaction submission adds
         *     a failure mode with no upside, and a retry of a business call must not re-upload a file.
         *
         *     `publicHash` is SHA-256 of the bytes the client is about to upload, supplied by the client and
         *     re-checked on receipt. It is the value that ends up anchored, so a mismatch rejects the upload
         *     rather than silently anchoring a digest of something else.
         */
        post: operations["presignDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List schemes. */
        get: operations["listSchemes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes/{schemeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public facts about one scheme, including its deployed contracts. */
        get: operations["getScheme"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes/{schemeId}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offers for a scheme. */
        get: operations["listOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offer terms, status and subscription progress. */
        get: operations["getOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offerId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pinned documents for an offer, with the digest anchored on-chain.
         * @description The bid book and the allotment file. `digest` is what a verifier compares against: fetch the
         *     bytes, hash them with SHA-256, and check. The CID is only a locator, which is why the digest is
         *     what gets anchored rather than the address.
         */
        get: operations["listOfferDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offerId}/ballot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The commit-reveal ceremony, as it stands.
         * @description Derived from `ballotrun.Ceremony`. Before the reveal, `seedPlaintext` and `finalSeed` are
         *     absent: that absence is the security property, since the secret is committed before the target
         *     block exists. After the reveal both are published, because by then there is nothing left to
         *     influence and the draw has to be reproducible by anyone.
         */
        get: operations["getBallot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offerId}/allotments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every bid's outcome, winners and losers alike.
         * @description Derived from `ballotrun.Line`. Identified only by leaf index and investor anchor, never by name
         *     or internal identifier. Losing bids are included deliberately: a bidder who won nothing is the
         *     one with the strongest reason to check the draw, and publishing only winners would make the
         *     outcome unfalsifiable for exactly those people.
         */
        get: operations["listAllotments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offerId}/proofs/bids/{bidRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merkle proof that a bid was in the frozen book.
         * @description Public by design. The bid reference is the investor's own receipt, like an application number,
         *     and the book is ordered by it precisely so a bidder can find their own leaf in the published
         *     document without being told anything they do not already hold.
         */
        get: operations["getBidProof"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes/{schemeId}/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distribution periods for a scheme. */
        get: operations["listPeriods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/periods/{periodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One distribution period. */
        get: operations["getPeriod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/periods/{periodId}/ndcf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The NDCF statement and the distribution ratio achieved.
         * @description Derived from `ndcf.Result`. `distributionBps` against `floorBps` is the statutory 95% test. The
         *     floor applies to NDCF, not to gross rent.
         */
        get: operations["getNdcfStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/periods/{periodId}/proofs/entitlements/{walletAddress}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merkle proof of a holder's entitlement for a period.
         * @description Keyed by wallet address rather than by investor anchor. The anchor is an HMAC under a key held
         *     in KMS, so a holder cannot compute their own; requiring it would mean AcreSync had to hand over
         *     a value only AcreSync can derive, which would defeat the purpose of publishing proofs at all.
         *
         *     Returns the gross entitlement only. Net of tax is not published, because publishing it beside a
         *     public unit count would disclose the holder's tax classification.
         */
        get: operations["getEntitlementProof"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated investor's profile and onboarding state. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Units held, per scheme. */
        get: operations["listMyHoldings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The investor's bids, with funds-block and allotment state. */
        get: operations["listMyBids"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entitlements per period, gross, tax withheld and net.
         * @description Derived from `entitlement.Line`. Unlike the public proof endpoint this includes the tax
         *     deduction and the net figure, because it is the holder's own record.
         */
        get: operations["listMyEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Payout instructions and their settlement state. */
        get: operations["listMyPayouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offerId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Place a bid and request the funds block.
         * @description Creates the bid and asks the investor's bank to block the full amount. Under ASBA the money
         *     stays in the investor's own account and is only debited to the extent units are allotted, so
         *     this call reserves rather than collects.
         *
         *     A block is all or nothing. An account short of the full amount fails rather than partially
         *     reserving, because a partial block is not a smaller valid bid: it would leave the bid unpayable
         *     by exactly the shortfall, and the failure would surface at debit time after the cap table was
         *     already anchored.
         */
        post: operations["placeBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an offer in CONFIGURED. */
        post: operations["createOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether the offer can advance, and what is blocking it.
         * @description Evaluates `offer.Guard` without performing anything. This is the endpoint an operator console
         *     should be built around: rather than offering a button that fails, it reports the next expected
         *     status and a list of unmet preconditions in the domain's own words.
         */
        get: operations["getOfferReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance the offer to the next status.
         * @description Refused unless every precondition for the target status holds. An abort additionally requires a
         *     reason, because an abort with no recorded cause is indistinguishable from a mistake.
         */
        post: operations["advanceOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/book/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Freeze the bid book, compute its root, pin it and queue the anchor.
         * @description Fixes the set of bids. Every bid in the book must hold a confirmed funds block covering exactly
         *     units times price; a block placed before a correction is still BLOCKED while covering the wrong
         *     amount, and admitting it would defer the failure to debit time.
         */
        post: operations["freezeBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/ballot/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anchor the seed commitment.
         * @description Takes no secret and no block number. The secret is derived from the scheme and offer under a KMS
         *     pepper, and the contract chooses the target block: a caller who could pick the block would pick
         *     one whose hash it had reason to prefer, and the ceremony would prove nothing.
         */
        post: operations["commitSeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/ballot/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal the secret and derive the final seed.
         * @description Valid only while `targetBlock < currentBlock <= targetBlock + revealWindowBlocks`. The lower
         *     bound is strict because a block's hash is not determined until the block after it.
         */
        post: operations["revealSeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/ballot/recommit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reroll the target block after a lapsed reveal window.
         * @description Reuses the stored commitment, so only the block hash is rerolled. Permitted only once the window
         *     has actually lapsed: recommitting while a reveal is still possible would let an operator who can
         *     already compute the draw abandon it and roll again. Capped at three attempts, after which a
         *     trustee must escalate.
         */
        post: operations["recommitSeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/ballot/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the allocation, pin the allotment file and queue the result anchor. */
        post: operations["drawBallot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/settlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The settlement plan, the chain's cursor, and whether finalisation would succeed.
         * @description `finalisation.failures` lists every unmet invariant rather than the first. The contract reverts
         *     on the earliest failure, so an operator fixing them one at a time would need a fresh transaction
         *     to discover the next.
         */
        get: operations["getSettlement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/settlement/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open settlement, binding it permanently to the anchored ballot result.
         * @description `expectedUnits` and `expectedHolders` cover the public side only. The manager's units are
         *     credited separately and outside the settlement cursor, so declaring the scheme total here would
         *     make every batch fail the running check.
         */
        post: operations["beginSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/settlement/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Credit the next batch of holders.
         * @description `cursorFrom` must equal the number of holders already credited, exactly. Batches cannot overlap,
         *     skip or be reordered. A batch that ran out of gas did not advance the cursor and is retryable
         *     verbatim with the same idempotency key; a batch that succeeded is rejected by both the key and
         *     the cursor.
         */
        post: operations["submitSettlementBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{offerId}/settlement/finalise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close settlement and move the scheme to Settled.
         * @description Permissionless on-chain, deliberately: if only the operator could finalise, the honest answer to
         *     "so you control the final cap table" would be yes. Five invariants must hold, and a failed
         *     attempt leaves the settlement open so it can be corrected and retried.
         */
        post: operations["finaliseSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/periods/{periodId}/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Depository register against the on-chain mirror.
         * @description Derived from `period.Reconciliation`. When `blocksPayout` is true a divergence exists and the
         *     database itself refuses to instruct payouts until it is resolved.
         */
        get: operations["getReconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The chain transaction queue. */
        get: operations["listOutbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int64
         * @description An integer count of paise. 100 paise is one rupee.
         * @example 100000000
         */
        Paise: number;
        /**
         * @description A SHA-256 digest or Merkle root, 0x-prefixed lowercase hex.
         * @example 0x77467d592e66a60dd201ec919080ea66eedf1f8b32171fc9bbfa88761937b7ad
         */
        Bytes32: string;
        /**
         * @description An Ethereum address, lowercase.
         * @example 0xf858a002402e968d1c7ec62c3824d30520e9ca38
         */
        Address: string;
        /**
         * @description What a presigned upload is for. Determines where it is filed and whether it is anchored.
         * @enum {string}
         */
        DocumentPurpose: "KYC" | "VALUATION_REPORT" | "OFFER_DOCUMENT" | "TRUSTEE_ESCROW" | "RENT_EVIDENCE" | "OTHER";
        /**
         * @description The investor's bid reference, 16 bytes as hex. Their receipt for the bid.
         * @example 9e107d9d372bb6826bd81d3542a419d6
         */
        BidRef: string;
        /** @description Cursor for the next page, or null when this is the last page. */
        NextCursor: string | null;
        /**
         * Format: date-time
         * @description RFC 3339, UTC, Z-suffixed.
         * @example 2026-05-09T11:00:00Z
         */
        Timestamp: string;
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "precondition_failed" | "not_feasible" | "anchor_not_confirmed" | "ceremony_order" | "units_issued" | "settlement_incomplete" | "validation_failed" | "idempotency_conflict" | "paused" | "not_found" | "unauthorized" | "forbidden" | "internal";
                /**
                 * @description The domain's own explanation, passed through rather than replaced. These sentences state
                 *     what is wrong and usually why it matters, and they are safe to surface to an operator.
                 */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                requestId?: string;
            };
        };
        /**
         * @description Mirrors `offer.Status` and the `offer_status` database enum.
         * @enum {string}
         */
        OfferStatus: "CONFIGURED" | "OPEN" | "CLOSED" | "BOOK_FROZEN" | "FEASIBILITY_CHECKED" | "BIDBOOK_ANCHORED" | "SEED_COMMITTED" | "SEED_REVEALED" | "BALLOT_DRAWN" | "ALLOTMENT_FINALISED" | "SETTLED" | "ABORTED";
        /**
         * @description Mirrors `ballotrun.Stage` and the `ballot_status` database enum.
         * @enum {string}
         */
        BallotStage: "PENDING" | "BIDBOOK_ANCHORED" | "SEED_COMMITTED" | "SEED_REVEALED" | "DRAWN" | "RESULT_ANCHORED" | "ESCALATED" | "ABANDONED";
        /**
         * @description Mirrors `ballot.Outcome`. The order is significant: the numeric position is part of the allotment
         *     leaf preimage and must match the Solidity enum.
         * @enum {string}
         */
        AllocationOutcome: "FULL" | "PARTIAL" | "NIL_BALLOT" | "NIL_TECHNICAL";
        /**
         * @description Mirrors `asba.BlockStatus`. Only BLOCKED holds funds. DEBITED and UNBLOCKED are both terminal and
         *     both mean the reservation is released; only DEBITED moved money.
         * @enum {string}
         */
        AsbaBlockStatus: "REQUESTED" | "BLOCKED" | "DEBITED" | "UNBLOCKED" | "FAILED";
        /**
         * @description Mirrors `period.Status`.
         * @enum {string}
         */
        PeriodStatus: "OPEN" | "RENT_COLLECTED" | "NDCF_DRAFTED" | "NDCF_APPROVED" | "RECORD_DATE_DECLARED" | "SNAPSHOT_TAKEN" | "RECONCILED" | "CHAIN_STALE" | "ANCHORED" | "ENTITLEMENTS_ANCHORED" | "PAYOUT_INSTRUCTED" | "PAYOUTS_CONFIRMED" | "CLOSED" | "REVERSED";
        /**
         * @description Mirrors `payout.DBStatus`, which is AcreSync's own vocabulary. Deliberately not the payment
         *     provider's set, so the frontend never depends on a vendor's words.
         *
         *     SETTLED is not the end of the story: a settled payout can still be reversed by the bank, which is
         *     why REVERSED exists as a distinct state rather than being folded into FAILED.
         * @enum {string}
         */
        PayoutStatus: "QUEUED" | "SUBMITTED" | "PROCESSING" | "SETTLED" | "FAILED" | "REVERSED";
        /**
         * @description Mirrors `entitlement.InvestorClass`. Determines the withholding rate.
         * @enum {string}
         */
        InvestorClass: "RESIDENT_IND" | "NRI" | "BODY_CORPORATE" | "HUF";
        /**
         * @description Mirrors `ndcf.LineType`.
         * @enum {string}
         */
        NdcfLineType: "GROSS_RENT" | "CAM_RECOVERY" | "INTEREST_INCOME" | "PROPERTY_TAX" | "INSURANCE" | "MAINTENANCE" | "TRUSTEE_FEE" | "IM_FEE" | "VALUER_FEE" | "AUDIT_FEE" | "STATUTORY_RESERVE" | "WORKING_CAPITAL_RESERVE" | "DEBT_SERVICE" | "OTHER";
        /** @enum {string} */
        NdcfDirection: "INFLOW" | "OUTFLOW";
        /**
         * @description Mirrors `period.ReconciliationStatus`.
         * @enum {string}
         */
        ReconciliationStatus: "MATCHED" | "DIVERGED" | "RESOLVED";
        /**
         * @description Mirrors the contract's SettlementStage enum, whose ordinals are NOT_STARTED 0, IN_PROGRESS 1,
         *     FINALISED 2. Exposed as a name rather than a number.
         * @enum {string}
         */
        SettlementStage: "NOT_STARTED" | "IN_PROGRESS" | "FINALISED";
        /** @enum {string} */
        OutboxStatus: "QUEUED" | "SIGNED" | "BROADCAST" | "PENDING" | "CONFIRMING" | "CONFIRMED" | "FAILED" | "REORGED" | "DEAD_LETTER" | "CANCELLED";
        Scheme: {
            /** Format: uuid */
            id: string;
            /** @example SEBI/SM-REIT/2026/001 */
            sebiSchemeRef: string;
            /** @example AcreSync Whitefield Scheme I */
            name: string;
            /**
             * @description ₹50 crore is the statutory floor for an SM-REIT scheme.
             * @example 50000000000
             */
            assetValuePaise?: components["schemas"]["Paise"];
            /**
             * @description ₹10 lakh per unit.
             * @example 100000000
             */
            unitPricePaise: components["schemas"]["Paise"];
            /**
             * Format: int32
             * @example 500
             */
            totalUnits: number;
            /**
             * Format: int32
             * @description Units the investment manager must hold. Excluded from the statutory holder count.
             * @example 25
             */
            imUnits: number;
            /**
             * Format: int32
             * @example 475
             */
            publicUnits: number;
            /**
             * Format: int32
             * @description Statutory floor. At least 200 for an SM-REIT.
             * @example 200
             */
            minPublicHolders: number;
            /**
             * @description Minimum share of NDCF to distribute, in basis points. 9500 is 95%.
             * @example 9500
             */
            distributionFloorBps: number;
            /**
             * @description Lifecycle status as recorded on-chain.
             * @example Operational
             */
            schemeStatus?: string;
            /**
             * @description Written into every anchor and admin action so a simulated record can never be mistaken for a
             *     live one.
             * @enum {string}
             */
            environmentTag: "LOCAL" | "SEPOLIA_SIM";
            contracts?: {
                /** @example 11155111 */
                chainId?: number;
                roles?: components["schemas"]["Address"];
                ballot?: components["schemas"]["Address"];
                scheme?: components["schemas"]["Address"];
            };
        };
        /** @description Mirrors `offer.Terms`, which mirrors the offers table and its constraints. */
        OfferTerms: {
            /**
             * Format: int32
             * @example 475
             */
            unitsOnOffer: number;
            /**
             * Format: int32
             * @example 1
             */
            minBidUnits: number;
            /**
             * Format: int32
             * @description Capped so the holder floor stays reachable. The largest permissible value is
             *     `unitsOnOffer - (minDistinctHolders - 1)`; above that the offer could be fully subscribed in
             *     rupees and still be unlistable.
             * @example 25
             */
            maxBidUnits: number;
            /**
             * Format: int32
             * @example 428
             */
            minSubscriptionUnits: number;
            /**
             * Format: int32
             * @example 200
             */
            minDistinctHolders: number;
            /**
             * @description Never below ₹10 lakh, the statutory minimum unit price.
             * @example 100000000
             */
            priceBandLowerPaise: components["schemas"]["Paise"];
            /** @example 105000000 */
            priceBandUpperPaise: components["schemas"]["Paise"];
            opensAt: components["schemas"]["Timestamp"];
            closesAt: components["schemas"]["Timestamp"];
            allotmentDueAt: components["schemas"]["Timestamp"];
        };
        Offer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            schemeId: string;
            /** @enum {string} */
            offerType: "INITIAL" | "FOLLOW_ON";
            status: components["schemas"]["OfferStatus"];
            terms: components["schemas"]["OfferTerms"];
            /** @description Present once bidding has begun. */
            subscription?: {
                /** @example 490 */
                bidCount?: number;
                /** @example 490 */
                distinctBidders?: number;
                /**
                 * Format: int64
                 * @example 980
                 */
                unitsBid?: number;
                /** @example 490 */
                fundsBlockedCount?: number;
                /**
                 * Format: int64
                 * @example 980
                 */
                oversubscriptionNumerator?: number;
                /**
                 * Format: int64
                 * @example 475
                 */
                oversubscriptionDenominator?: number;
            };
            createdAt?: components["schemas"]["Timestamp"];
        };
        CreateOfferRequest: {
            /** Format: uuid */
            schemeId: string;
            /** @enum {string} */
            offerType: "INITIAL" | "FOLLOW_ON";
            terms: components["schemas"]["OfferTerms"];
        };
        Readiness: {
            currentStatus: components["schemas"]["OfferStatus"];
            /** @description The next status on the happy path, or null at a terminal status. */
            nextExpected?: components["schemas"]["OfferStatus"] | null;
            canAdvance: boolean;
            /**
             * @description Unmet preconditions, in the domain's own words. Empty when `canAdvance` is true.
             * @example [
             *       "3 bid(s) are still awaiting validation; freezing now would fix a book that is still changing"
             *     ]
             */
            blockers: string[];
            paused?: boolean;
        };
        PlaceBidRequest: {
            /**
             * Format: int32
             * @example 2
             */
            unitsBid: number;
            pricePerUnitPaise: components["schemas"]["Paise"];
            /**
             * Format: uuid
             * @description Where allotted units are credited. Required before money is blocked for them.
             */
            dematAccountId: string;
            /** Format: uuid */
            bankAccountId: string;
        };
        Bid: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            offerId: string;
            bidRef: components["schemas"]["BidRef"];
            investorAnchor?: components["schemas"]["Bytes32"];
            /**
             * Format: int32
             * @example 2
             */
            unitsBid: number;
            pricePerUnitPaise: components["schemas"]["Paise"];
            totalAmountPaise: components["schemas"]["Paise"];
            /**
             * @description Mirrors the `bid_status` database enum.
             * @enum {string}
             */
            status: "SUBMITTED" | "BLOCK_REQUESTED" | "FUNDS_BLOCKED" | "VALIDATED" | "IN_BOOK" | "ALLOTTED_FULL" | "ALLOTTED_PARTIAL" | "REJECTED_BALLOT" | "REJECTED_TECHNICAL" | "DEBIT_INSTRUCTED" | "FUNDS_DEBITED" | "UNITS_CREDITED" | "ANCHORED" | "UNBLOCK_REQUESTED" | "FUNDS_UNBLOCKED";
            /**
             * @description Set whenever the status is REJECTED_BALLOT or REJECTED_TECHNICAL, and only then. A rejected
             *     bid keeps this status even after its funds are released, because the release is recorded on
             *     the block rather than by moving the bid out of a state that carries the reason.
             * @enum {string|null}
             */
            rejectionReason?: "BALLOT_NOT_DRAWN" | "KYC_INVALID" | "KYC_EXPIRED" | "DEMAT_UNVERIFIED" | "ASBA_BLOCK_FAILED" | "BELOW_MIN_BID" | "ABOVE_MAX_BID" | "DUPLICATE_BID" | "OFFER_ABORTED" | null;
            block?: components["schemas"]["AsbaBlock"];
            /** @description Present once the draw has run. */
            allotment?: components["schemas"]["BidAllotment"] | null;
            submittedAt?: components["schemas"]["Timestamp"];
        };
        /**
         * @description Mirrors `asba.Block`. The money never leaves the investor's account: the bank marks it
         *     unavailable and debits only the allotted portion. There is deliberately no house balance
         *     anywhere in this API, because modelling one would model a custody arrangement AcreSync does not
         *     have.
         */
        AsbaBlock: {
            status: components["schemas"]["AsbaBlockStatus"];
            requestedAmountPaise: components["schemas"]["Paise"];
            /** @description Equal to the requested amount or absent. A partial block is never recorded. */
            blockedAmountPaise?: components["schemas"]["Paise"] | null;
            debitedAmountPaise?: components["schemas"]["Paise"] | null;
            /**
             * @description Stored rather than derived. `debited + released == blocked` holds with no tolerance, and
             *     recording both halves makes that provable from what was written.
             */
            releasedAmountPaise?: components["schemas"]["Paise"] | null;
            failureCode?: string | null;
            blockedAt?: components["schemas"]["Timestamp"] | null;
        };
        BidAllotment: {
            /**
             * Format: int32
             * @example 1
             */
            unitsAllotted: number;
            outcome: components["schemas"]["AllocationOutcome"];
            /**
             * Format: int32
             * @description The bid's position in the draw. Recomputable by anyone from the published seed, the investor
             *     anchor and the leaf index, which is what lets a losing bidder confirm their position was not
             *     invented.
             * @example 37
             */
            ballotRank: number;
            amountPayablePaise: components["schemas"]["Paise"];
            refundAmountPaise: components["schemas"]["Paise"];
        };
        /** @description One line of the published allotment file. Carries no identifiers. */
        PublishedAllotment: {
            /** Format: int32 */
            leafIndex: number;
            investorAnchor: components["schemas"]["Bytes32"];
            /** Format: int32 */
            unitsAllotted: number;
            outcome: components["schemas"]["AllocationOutcome"];
            /** Format: int32 */
            ballotRank: number;
        };
        BallotCeremony: {
            /** Format: uuid */
            offerId: string;
            stage: components["schemas"]["BallotStage"];
            bidbookRoot?: components["schemas"]["Bytes32"] | null;
            bidbookCidDigest?: components["schemas"]["Bytes32"] | null;
            /** @description SHA-256 of the secret. Immutable once set; a recommit reuses it. */
            seedCommitment?: components["schemas"]["Bytes32"] | null;
            /**
             * Format: int64
             * @description Chosen by the contract, never by the caller.
             */
            targetBlock?: number | null;
            /** @example 200 */
            revealWindowBlocks?: number;
            /** Format: int64 */
            revealDeadlineBlock?: number | null;
            /** @description Absent until revealed. Its absence before the target block is the security property. */
            seedPlaintext?: components["schemas"]["Bytes32"] | null;
            targetBlockHash?: components["schemas"]["Bytes32"] | null;
            /** @description SHA-256 over the secret, the target block hash and the bid book root. */
            finalSeed?: components["schemas"]["Bytes32"] | null;
            resultRoot?: components["schemas"]["Bytes32"] | null;
            /**
             * @description Commit attempts used, from 1. Capped at maxAttempts, after which a trustee escalates.
             * @example 1
             */
            attempt: number;
            /** @example 3 */
            maxAttempts: number;
            escalated?: boolean;
        };
        BookFreezeResult: {
            /** Format: uuid */
            offerId: string;
            merkleRoot: components["schemas"]["Bytes32"];
            /**
             * Format: int32
             * @example 490
             */
            leafCount: number;
            /**
             * Format: int64
             * @example 980
             */
            totalUnitsBid: number;
            /**
             * Format: int32
             * @example 490
             */
            distinctBidders: number;
            frozenAt: components["schemas"]["Timestamp"];
            feasibility?: {
                feasible?: boolean;
                subscriptionMet?: boolean;
                holderFloorMet?: boolean;
                fullSubscriptionMet?: boolean;
                reasons?: string[];
            };
            document?: components["schemas"]["PublishedDocument"];
        };
        DrawResult: {
            /** Format: uuid */
            offerId: string;
            finalSeed: components["schemas"]["Bytes32"];
            bidbookRoot: components["schemas"]["Bytes32"];
            resultRoot: components["schemas"]["Bytes32"];
            /**
             * Format: int32
             * @example 475
             */
            unitsAllotted: number;
            /**
             * Format: int32
             * @example 475
             */
            distinctAllottees: number;
            /**
             * @description Version of the allocation rules. A verifier reproducing a historical allotment needs to know
             *     which rules applied.
             * @example 1
             */
            algoVersion: number;
            outcomeCounts?: {
                /** @example 0 */
                full?: number;
                /** @example 475 */
                partial?: number;
                /** @example 15 */
                nilBallot?: number;
                /** @example 0 */
                nilTechnical?: number;
            };
            document?: components["schemas"]["PublishedDocument"];
        };
        SettlementState: {
            /** Format: uuid */
            offerId: string;
            stage: components["schemas"]["SettlementStage"];
            /**
             * Format: int32
             * @description Public side only. The manager's units are credited outside the cursor.
             * @example 475
             */
            expectedUnits: number;
            /**
             * Format: int32
             * @example 475
             */
            expectedHolders: number;
            /**
             * Format: int32
             * @example 200
             */
            creditedUnits: number;
            /**
             * Format: int32
             * @description Also the cursor. The next batch must declare exactly this value as `cursorFrom`.
             * @example 200
             */
            creditedHolders: number;
            allotmentFileHash?: components["schemas"]["Bytes32"];
            ballotResultRoot?: components["schemas"]["Bytes32"];
            /**
             * @description Whether the manager's subscription is on-chain. Easily forgotten because the manager never
             *     bids, and without it the register is short by exactly its holding.
             */
            imUnitsRecorded?: boolean;
            batches?: {
                /** Format: int32 */
                cursorFrom?: number;
                /** Format: int32 */
                cursorTo?: number;
                holderCount?: number;
                /**
                 * Format: int32
                 * @description Units this batch credits.
                 */
                units?: number;
                submitted?: boolean;
            }[];
            /** @enum {string|null} */
            nextStep?: "beginSettlement" | "settleBatch" | "finaliseSettlement" | null;
            finalisation?: {
                ready?: boolean;
                /** @description Every unmet invariant, not merely the first. */
                failures?: string[];
            };
        };
        PublishedDocument: {
            /** @enum {string} */
            docType: "BIDBOOK" | "ALLOTMENT_FILE" | "NDCF_STATEMENT" | "SNAPSHOT" | "VALUATION" | "OFFER_DOCUMENT";
            /**
             * @description SHA-256 of the canonical document bytes. This is the commitment anchored on-chain. Verify by
             *     fetching the bytes and hashing them.
             */
            digest: components["schemas"]["Bytes32"];
            /**
             * @description IPFS address. A locator only, never the commitment.
             * @example bafkreieq5jui4j25lacwomsqgjeswwl3y5zcdrresptwgmfylxo2depppq
             */
            cid?: string | null;
            /** Format: uri */
            gatewayUrl?: string | null;
            byteSize?: number | null;
            /**
             * @description Whether the document fits one raw IPFS block. Above that a provider chunks it and the root
             *     block's digest is no longer the document's digest.
             */
            singleBlock?: boolean | null;
            codecVerified?: boolean | null;
            anchoredTx?: string | null;
            anchorConfirmations?: number | null;
        };
        InclusionProof: {
            /** Format: int32 */
            leafIndex: number;
            leaf: components["schemas"]["Bytes32"];
            /** @description Sibling digests from leaf to root. Fold with SHA-256, ordering each pair by value. */
            proof: components["schemas"]["Bytes32"][];
            root: components["schemas"]["Bytes32"];
            /**
             * @description Whether AcreSync's own recomputation succeeds. A convenience, not evidence: the point of the
             *     proof is that a verifier checks it themselves against the root anchored on-chain.
             */
            verified: boolean;
            anchoredTx?: string | null;
            /** @description The fields hashed to form the leaf, so a verifier can rebuild it without guessing. */
            preimage?: {
                [key: string]: unknown;
            };
        };
        Period: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            schemeId: string;
            /** @example 1 */
            periodSeq: number;
            /**
             * Format: date
             * @example 2026-07-01
             */
            periodStart: string;
            /**
             * Format: date
             * @example 2026-09-30
             */
            periodEnd: string;
            /** Format: date */
            recordDate?: string | null;
            status: components["schemas"]["PeriodStatus"];
            /** @description Present once the register is frozen for the period. */
            snapshot?: {
                merkleRoot?: components["schemas"]["Bytes32"];
                /**
                 * Format: int32
                 * @description The entitlement denominator. All units, manager included.
                 * @example 500
                 */
                totalUnits?: number;
                /**
                 * Format: int32
                 * @description Statutory count, excluding the manager.
                 * @example 475
                 */
                distinctHolders?: number;
                /**
                 * @description Register lines. Exceeds distinctHolders by the excluded manager.
                 * @example 476
                 */
                lineCount?: number;
                takenAt?: components["schemas"]["Timestamp"];
            };
        };
        NdcfStatement: {
            /** Format: uuid */
            periodId: string;
            /** @enum {string} */
            currency: "INR";
            ndcfPaise: components["schemas"]["Paise"];
            totalInflowPaise?: components["schemas"]["Paise"];
            totalOutflowPaise?: components["schemas"]["Paise"];
            reservePaise?: components["schemas"]["Paise"];
            feePaise?: components["schemas"]["Paise"];
            /**
             * @description The 95% floor applied to NDCF, rounded up. Rounding down would fall short by a paise whenever
             *     the division is inexact, and then fail the floor by exactly that paise.
             */
            minimumDistributablePaise?: components["schemas"]["Paise"];
            distributedPaise: components["schemas"]["Paise"];
            /** @example 9500 */
            floorBps: number;
            /**
             * @description Achieved ratio. Compared against the floor by cross-multiplication rather than by computing a
             *     percentage, because multiplying the distributed amount by 10000 would overflow.
             * @example 9500
             */
            distributionBps: number;
            statementDigest?: components["schemas"]["Bytes32"];
            lineItems: {
                lineType: components["schemas"]["NdcfLineType"];
                direction: components["schemas"]["NdcfDirection"];
                amountPaise: components["schemas"]["Paise"];
                /** Format: uuid */
                spvRef?: string | null;
                /** Format: uuid */
                propertyRef?: string | null;
                evidenceHash?: components["schemas"]["Bytes32"];
            }[];
            document?: components["schemas"]["PublishedDocument"];
        };
        Me: {
            /** Format: uuid */
            investorId: string;
            /** @example A. Investor */
            displayName?: string;
            investorClass: components["schemas"]["InvestorClass"];
            /** @enum {string} */
            kycStatus: "PENDING" | "VERIFIED" | "REJECTED" | "EXPIRED";
            /**
             * @description Last four characters only. The full value is never returned by this API.
             * @example XXXXX1234F
             */
            panMasked?: string | null;
            walletAddress?: components["schemas"]["Address"] | null;
            dematAccounts?: {
                /** Format: uuid */
                id?: string;
                /** @enum {string} */
                depository?: "NSDL" | "CDSL";
                /** @example ****4821 */
                maskedClientId?: string;
                verified?: boolean;
            }[];
            bankAccounts?: {
                /** Format: uuid */
                id?: string;
                /** @example HDFC0001234 */
                ifsc?: string;
                /** @example ****3310 */
                maskedAccountNumber?: string;
                verified?: boolean;
            }[];
        };
        Holding: {
            /** Format: uuid */
            schemeId: string;
            schemeName?: string;
            walletAddress?: components["schemas"]["Address"];
            /**
             * Format: int32
             * @example 2
             */
            units: number;
            /**
             * @description True only for the investment manager. Excluded from the statutory holder count, not from the
             *     distribution: the entitlement denominator is all units.
             */
            excludedFromHolderCount?: boolean;
            /** @description Null until listing. The manager's two-year hold runs from listing, not subscription. */
            lockInExpiresAt?: components["schemas"]["Timestamp"] | null;
            firstCreditedAt?: components["schemas"]["Timestamp"];
        };
        MyEntitlement: {
            /** Format: uuid */
            periodId: string;
            /** Format: date */
            periodEnd?: string;
            /** Format: int32 */
            leafIndex?: number;
            /**
             * Format: int32
             * @example 2
             */
            units: number;
            /**
             * Format: int32
             * @example 500
             */
            snapshotTotalUnits?: number;
            /** @description Units divided by the snapshot total, times the distributed amount. */
            grossPaise: components["schemas"]["Paise"];
            tax?: {
                investorClass?: components["schemas"]["InvestorClass"];
                /** @example 194LBA */
                section?: string;
                /** @example 1000 */
                rateBps?: number;
                amountPaise?: components["schemas"]["Paise"];
                form15GHOnFile?: boolean;
            };
            netPayablePaise: components["schemas"]["Paise"];
            /**
             * @description False when the amount is below the provider's minimum. An amount between 1 and 99 paise is
             *     storable and unpayable, and carries forward rather than being silently dropped.
             */
            payable?: boolean;
            payout?: components["schemas"]["Payout"] | null;
        };
        Payout: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            periodId?: string;
            amountPaise: components["schemas"]["Paise"];
            status: components["schemas"]["PayoutStatus"];
            /** @description The bank's transaction reference, once settled. */
            utr?: string | null;
            settledAt?: components["schemas"]["Timestamp"] | null;
            failureCode?: string | null;
            /**
             * @description Incremented only on a reissue, never on a retry. A retry of the same instruction must reuse
             *     its key so it cannot double-pay.
             * @example 0
             */
            attempt?: number;
            /** @enum {string} */
            provider?: "MOCK" | "RAZORPAYX_SANDBOX";
            /** @description True whenever the provider is MOCK. Surfaced so a demo can never be mistaken for a payment. */
            simulated?: boolean;
        };
        Reconciliation: {
            /** Format: uuid */
            periodId: string;
            status: components["schemas"]["ReconciliationStatus"];
            /** Format: int32 */
            depositoryTotalUnits: number;
            /** Format: int32 */
            chainTotalUnits: number;
            depositoryHolderCount?: number;
            chainHolderCount?: number;
            /**
             * @description When true the database itself refuses to instruct payouts. Paying against a register known to
             *     be wrong is the one failure that cannot be corrected afterwards.
             */
            blocksPayout: boolean;
            diffs?: {
                walletAddress?: components["schemas"]["Address"];
                /** Format: int32 */
                depositoryUnits?: number;
                /** Format: int32 */
                chainUnits?: number;
                /** Format: int64 */
                diffUnits?: number;
            }[];
        };
        OutboxEntry: {
            /** Format: uuid */
            id: string;
            targetContract?: components["schemas"]["Address"];
            /** @example anchorBidbook */
            functionName: string;
            status: components["schemas"]["OutboxStatus"];
            /** Format: int64 */
            nonce?: number | null;
            txHash?: string | null;
            /** Format: int64 */
            blockNumber?: number | null;
            confirmations?: number;
            attempts?: number;
            lastError?: string | null;
            /** @enum {string} */
            environmentTag: "LOCAL" | "SEPOLIA_SIM";
            createdAt?: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description The action is not permitted in the current state. `code` distinguishes why: `precondition_failed`,
         *     `not_feasible`, `anchor_not_confirmed`, `ceremony_order`, `units_issued`, `settlement_incomplete`
         *     or `idempotency_conflict`.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "anchor_not_confirmed",
                 *         "message": "the bid book anchor needs 5 confirmations before the draw is bound to it; a reorg afterwards would leave the commitment bound to a book the chain no longer records",
                 *         "requestId": "req_01HQ8Z3M"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The request was well-formed but a business rule rejected it. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The scheme is paused. Everything except an abort is refused. */
        Paused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Nothing has changed since the `ETag` supplied in `If-None-Match`. No body. This is the normal
         *     answer to most polls.
         */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Malformed parameters, such as an unparseable cursor or an out-of-range limit. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated, but this role may not perform the action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        SchemeId: string;
        OfferId: string;
        PeriodId: string;
        /** @description Page size. Defaults to 50. */
        Limit: number;
        /** @description Opaque cursor from the previous response's `nextCursor`. */
        Cursor: string;
        /**
         * @description The `ETag` from the previous response. When the state has not changed the server answers `304` with
         *     no body, which is what makes a 3-second poll cheap.
         *
         *     Required for a 304 to be meaningful: an unconditional request cannot receive one, so a poller that
         *     omits this header simply gets the full body every time.
         */
        IfNoneMatch: string;
        /**
         * @description Mock and development only. Impersonates an operator role without issuing separate tokens. Ignored
         *     by any deployed environment.
         */
        MockRole: "MANAGER" | "TRUSTEE" | "COMPLIANCE";
        /**
         * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
         *     the original response; replaying it with a different body is a conflict. Required on every
         *     mutation, because a retry after a dropped connection must not place a second funds block or
         *     anchor a second transaction.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Present and true when this response was replayed from a previous identical request. */
        IdempotencyReplayed: boolean;
        /**
         * @description Opaque state version. Send it back as `If-None-Match` while polling to receive `304` until
         *     something actually changes.
         */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The Web3Auth-issued JWT. */
                    idToken: string;
                };
            };
        };
        responses: {
            /** @description A session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Send as an `Authorization` bearer header on investor endpoints. */
                        accessToken: string;
                        expiresAt: components["schemas"]["Timestamp"];
                        /**
                         * Format: uuid
                         * @description The internal investor identifier. A UUID, because that is what the register uses.
                         * @example 1e7d4c6a-0000-4000-8000-000000000001
                         */
                        investorId: string;
                        /** @enum {string} */
                        kycStatus?: "PENDING" | "VERIFIED" | "REJECTED" | "EXPIRED";
                    };
                };
            };
            /** @description The Web3Auth token is missing, expired or fails signature verification. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    presignDocument: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example valuation-q2-2026.pdf */
                    filename: string;
                    /** @example application/pdf */
                    mimeType: string;
                    purpose: components["schemas"]["DocumentPurpose"];
                    byteSize?: number;
                    /** @description SHA-256 the client computed locally. Re-verified server side. */
                    publicHash?: components["schemas"]["Bytes32"] | null;
                };
            };
        };
        responses: {
            /** @description An upload intent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Pass this to the business call that consumes the document.
                         */
                        documentId: string;
                        /**
                         * Format: uri
                         * @description Upload the bytes here with PUT. In local development this is a small multipart
                         *     handler rather than object storage.
                         */
                        uploadUrl: string;
                        expiresAt: components["schemas"]["Timestamp"];
                        publicHash?: components["schemas"]["Bytes32"] | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listSchemes: {
        parameters: {
            query?: {
                /** @description Page size. Defaults to 50. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from the previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of schemes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Scheme"][];
                        nextCursor?: components["schemas"]["NextCursor"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getScheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemeId: components["parameters"]["SchemeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The scheme. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scheme"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listOffers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemeId: components["parameters"]["SchemeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Offer"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The offer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listOfferDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents published for this offer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublishedDocument"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBallot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ceremony state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallotCeremony"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAllotments: {
        parameters: {
            query?: {
                /** @description Page size. Defaults to 50. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from the previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of allotments, ordered by leaf index. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublishedAllotment"][];
                        nextCursor?: components["schemas"]["NextCursor"];
                    };
                };
            };
            /** @description No such offer, or the draw has not run so there are no allotments to publish. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getBidProof: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
                /** @description The investor's bid reference. 32 lowercase hex characters. */
                bidRef: components["schemas"]["BidRef"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The proof and the leaf it proves. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InclusionProof"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPeriods: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemeId: components["parameters"]["SchemeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Periods, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Period"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPeriod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodId: components["parameters"]["PeriodId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The period. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Period"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getNdcfStatement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodId: components["parameters"]["PeriodId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The statement. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NdcfStatement"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getEntitlementProof: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodId: components["parameters"]["PeriodId"];
                walletAddress: components["schemas"]["Address"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The proof and the leaf it proves. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InclusionProof"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The investor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyHoldings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Holding"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyBids: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bids, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Bid"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyEntitlements: {
        parameters: {
            query?: {
                schemeId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entitlements, newest period first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MyEntitlement"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyPayouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payouts, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Payout"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    placeBid: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceBidRequest"];
            };
        };
        responses: {
            /** @description Bid accepted and the block requested. */
            201: {
                headers: {
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bid"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createOffer: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOfferRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getOfferReadiness: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The `ETag` from the previous response. When the state has not changed the server answers `304` with
                 *     no body, which is what makes a 3-second poll cheap.
                 *
                 *     Required for a 304 to be meaningful: an unconditional request cannot receive one, so a poller that
                 *     omits this header simply gets the full body every time.
                 */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
                /**
                 * @description Mock and development only. Impersonates an operator role without issuing separate tokens. Ignored
                 *     by any deployed environment.
                 */
                "X-Mock-Role"?: components["parameters"]["MockRole"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readiness. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            304: components["responses"]["NotModified"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    advanceOffer: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    to: components["schemas"]["OfferStatus"];
                    /** @description Required when `to` is ABORTED. */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            409: components["responses"]["Conflict"];
            423: components["responses"]["Paused"];
        };
    };
    freezeBook: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frozen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookFreezeResult"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    commitSeed: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commitment queued for anchoring. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallotCeremony"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    revealSeed: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reveal queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallotCeremony"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    recommitSeed: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommit queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallotCeremony"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    drawBallot: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drawn. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawResult"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlement state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementState"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    beginSettlement: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlement opening queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementState"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    submitSettlementBatch: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int32 */
                    cursorFrom: number;
                };
            };
        };
        responses: {
            /** @description Batch queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementState"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    finaliseSettlement: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated, unique per logical operation. Replaying the same key with the same body returns
                 *     the original response; replaying it with a different body is a conflict. Required on every
                 *     mutation, because a retry after a dropped connection must not place a second funds block or
                 *     anchor a second transaction.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finalisation queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementState"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodId: components["parameters"]["PeriodId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reconciliation"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listOutbox: {
        parameters: {
            query: {
                schemeId: string;
                status?: components["schemas"]["OutboxStatus"];
                /** @description Page size. Defaults to 50. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from the previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of outbox entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OutboxEntry"][];
                        nextCursor?: components["schemas"]["NextCursor"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
}
