// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";

import {MerkleLib} from "../src/MerkleLib.sol";
import {BallotEncoding} from "../src/BallotEncoding.sol";

/// @title Parity
/// @notice Holds the Solidity hashing and encoding to the same specification as Go.
///
/// @dev The vectors are generated by `orchestrator/cmd/genvectors` from the Go
/// implementation and committed. This test replays them through the Solidity library.
///
/// The failure this prevents is severe and quiet. If the two implementations disagree
/// on a single byte of a leaf preimage, every proof produced off-chain fails on-chain,
/// so `verifyEntitlement` rejects every honest investor while reporting nothing about
/// why. Because the contracts are immutable with no proxy, that is not a bug you patch.
contract ParityTest is Test {
    using stdJson for string;

    string internal vectors;

    function setUp() public {
        vectors = vm.readFile("./test/testdata/vectors.json");
    }

    // ---------------------------------------------------------------------
    // Merkle primitives
    // ---------------------------------------------------------------------

    function test_HashLeafMatchesGo() public view {
        bytes memory preimage = vectors.readBytes(".merkle.hashLeaf.preimageHex");
        bytes32 expected = vectors.readBytes32(".merkle.hashLeaf.out");

        assertEq(
            MerkleLib.hashLeaf(preimage),
            expected,
            "leaf hashing diverged from Go: every anchored root becomes unverifiable"
        );
    }

    function test_HashNodeMatchesGo() public view {
        bytes32 a = vectors.readBytes32(".merkle.hashNode.a");
        bytes32 b = vectors.readBytes32(".merkle.hashNode.b");
        bytes32 expected = vectors.readBytes32(".merkle.hashNode.out");

        assertEq(MerkleLib.hashNode(a, b), expected, "node hashing diverged from Go");
    }

    /// @dev Sorted pairs are what allow a proof to omit direction bits. If this ever
    /// stopped holding, every proof would need a bitmap and the whole verification path
    /// would change shape.
    function test_HashNodeIsOrderIndependent() public view {
        bytes32 a = vectors.readBytes32(".merkle.hashNode.a");
        bytes32 b = vectors.readBytes32(".merkle.hashNode.b");
        bytes32 expected = vectors.readBytes32(".merkle.hashNode.swapped");

        assertEq(MerkleLib.hashNode(b, a), expected, "swapped operands changed the hash");
        assertEq(MerkleLib.hashNode(a, b), MerkleLib.hashNode(b, a), "sorted pairing broken");
    }

    /// @dev Domain separation is the defence against presenting an internal node as a
    /// leaf. Without distinct prefixes a node hash is a valid hash of 64 bytes of leaf
    /// data, and membership of something that was never a leaf becomes provable.
    function test_LeafAndNodePrefixesDiffer() public pure {
        bytes32 a = sha256("a");
        bytes32 b = sha256("b");

        bytes32 asNode = MerkleLib.hashNode(a, b);
        bytes32 asLeaf = MerkleLib.hashLeaf(abi.encodePacked(a <= b ? a : b, a <= b ? b : a));

        assertTrue(asNode != asLeaf, "a leaf hash collided with a node hash over the same bytes");
    }

    // ---------------------------------------------------------------------
    // Proof verification across every committed tree
    // ---------------------------------------------------------------------

    /// @dev Iterates every tree and every proof in the vector file. Tree and proof
    /// counts are read from the file rather than hardcoded, so adding a case to the
    /// generator extends this test automatically instead of leaving it unverified.
    function test_AllProofsVerify() public view {
        uint256 treeCount = vectors.readUint(".merkle.treeCount");
        assertGt(treeCount, 0, "no trees in the vector file");

        uint256 totalProofs;

        for (uint256 t = 0; t < treeCount; t++) {
            string memory treePath = string.concat(".merkle.trees[", vm.toString(t), "]");
            bytes32 root = vectors.readBytes32(string.concat(treePath, ".root"));
            uint256 proofCount = vectors.readUint(string.concat(treePath, ".proofCount"));

            for (uint256 p = 0; p < proofCount; p++) {
                string memory proofPath =
                    string.concat(treePath, ".proofs[", vm.toString(p), "]");

                bytes32 leaf = vectors.readBytes32(string.concat(proofPath, ".leaf"));
                bytes32[] memory proof =
                    vectors.readBytes32Array(string.concat(proofPath, ".proof"));

                assertTrue(
                    MerkleLib.verify(root, leaf, proof),
                    string.concat("proof failed for ", treePath, " ", proofPath)
                );
                totalProofs++;
            }
        }

        // The 475-leaf tree is the real public offer size and is not a power of two, so
        // it exercises node promotion. If the generator ever stopped emitting it this
        // assertion notices.
        assertGe(totalProofs, 10, "too few proofs exercised to be meaningful");
    }

    /// @dev A single-leaf tree has the leaf as its root and an empty proof. Worth its own
    /// case because an off-by-one in the fold would still pass larger trees.
    function test_SingleLeafTree() public view {
        bytes32 root = vectors.readBytes32(".merkle.trees[0].root");
        bytes32 leaf = vectors.readBytes32(".merkle.trees[0].proofs[0].leaf");
        bytes32[] memory empty = new bytes32[](0);

        assertEq(root, leaf, "a single-leaf root must equal its leaf");
        assertTrue(MerkleLib.verify(root, leaf, empty), "empty proof must verify");
    }

    function test_WrongLeafFailsVerification() public view {
        bytes32 root = vectors.readBytes32(".merkle.trees[2].root");
        bytes32[] memory proof = vectors.readBytes32Array(".merkle.trees[2].proofs[0].proof");
        bytes32 wrongLeaf = sha256("definitely not in the tree");

        assertFalse(MerkleLib.verify(root, wrongLeaf, proof), "a foreign leaf verified");
    }

    function test_TamperedProofFails() public view {
        bytes32 root = vectors.readBytes32(".merkle.trees[4].root");
        bytes32 leaf = vectors.readBytes32(".merkle.trees[4].proofs[2].leaf");
        bytes32[] memory proof = vectors.readBytes32Array(".merkle.trees[4].proofs[2].proof");

        assertTrue(MerkleLib.verify(root, leaf, proof), "baseline proof should verify");

        proof[0] = bytes32(uint256(proof[0]) ^ 1);
        assertFalse(MerkleLib.verify(root, leaf, proof), "a tampered proof verified");
    }

    // ---------------------------------------------------------------------
    // Ballot encodings
    // ---------------------------------------------------------------------

    function test_BidLeafMatchesGo() public view {
        uint32 leafIndex = uint32(vectors.readUint(".ballot.bidLeaf.leafIndex"));
        bytes16 bidRef = bytes16(vectors.readBytes(".ballot.bidLeaf.bidRefBytes"));
        bytes32 anchor = vectors.readBytes32(".ballot.bidLeaf.investorAnchor");
        uint32 unitsBid = uint32(vectors.readUint(".ballot.bidLeaf.unitsBid"));
        uint64 price = uint64(vectors.readUint(".ballot.bidLeaf.pricePerUnitPaise"));
        bytes32 expected = vectors.readBytes32(".ballot.bidLeaf.leaf");

        assertEq(
            BallotEncoding.bidLeaf(leafIndex, bidRef, anchor, unitsBid, price),
            expected,
            "bid leaf encoding diverged from Go: bid book proofs would all fail"
        );
    }

    function test_AllotmentLeafMatchesGo() public view {
        uint32 leafIndex = uint32(vectors.readUint(".ballot.allotmentLeaf.leafIndex"));
        bytes32 anchor = vectors.readBytes32(".ballot.allotmentLeaf.investorAnchor");
        uint32 units = uint32(vectors.readUint(".ballot.allotmentLeaf.unitsAllotted"));
        uint8 code = uint8(vectors.readUint(".ballot.allotmentLeaf.outcomeCode"));
        uint32 rank = uint32(vectors.readUint(".ballot.allotmentLeaf.ballotRank"));
        bytes32 expected = vectors.readBytes32(".ballot.allotmentLeaf.leaf");

        assertEq(
            BallotEncoding.allotmentLeaf(leafIndex, anchor, units, code, rank),
            expected,
            "allotment leaf encoding diverged from Go"
        );
    }

    function test_FinalSeedMatchesGo() public view {
        bytes32 secret = vectors.readBytes32(".ballot.finalSeed.secret");
        bytes32 blockHash = vectors.readBytes32(".ballot.finalSeed.targetBlockHash");
        bytes32 bookRoot = vectors.readBytes32(".ballot.finalSeed.bidbookRoot");
        bytes32 expected = vectors.readBytes32(".ballot.finalSeed.out");

        assertEq(
            BallotEncoding.finalSeed(secret, blockHash, bookRoot),
            expected,
            "seed derivation diverged from Go: the draw could not be reproduced"
        );
    }

    function test_CommitmentMatchesGo() public view {
        bytes32 secret = vectors.readBytes32(".ballot.finalSeed.secret");
        bytes32 expected = vectors.readBytes32(".ballot.finalSeed.commitment");

        assertEq(
            BallotEncoding.commitmentOf(secret),
            expected,
            "commitment derivation diverged from Go: a valid reveal would be rejected"
        );
    }

    function test_RankKeyMatchesGo() public view {
        bytes32 seed = vectors.readBytes32(".ballot.finalSeed.out");
        bytes32 anchor = vectors.readBytes32(".ballot.finalSeed.rankKeyAnchor");
        uint32 leafIndex = uint32(vectors.readUint(".ballot.finalSeed.rankKeyLeafIndex"));
        bytes32 expected = vectors.readBytes32(".ballot.finalSeed.rankKeyOut");

        assertEq(
            BallotEncoding.rankKey(seed, anchor, leafIndex),
            expected,
            "rank key derivation diverged from Go: published ranks could not be checked"
        );
    }

    /// @dev Outcome codes are part of the allotment leaf preimage, so their numeric
    /// values are frozen. Reordering them would silently invalidate every anchored
    /// allotment root.
    function test_OutcomeCodesMatchGo() public view {
        assertEq(
            uint256(BallotEncoding.OUTCOME_FULL),
            vectors.readUint(".ballot.outcomeCodes.FULL"),
            "FULL"
        );
        assertEq(
            uint256(BallotEncoding.OUTCOME_PARTIAL),
            vectors.readUint(".ballot.outcomeCodes.PARTIAL"),
            "PARTIAL"
        );
        assertEq(
            uint256(BallotEncoding.OUTCOME_NIL_BALLOT),
            vectors.readUint(".ballot.outcomeCodes.NIL_BALLOT"),
            "NIL_BALLOT"
        );
        assertEq(
            uint256(BallotEncoding.OUTCOME_NIL_TECHNICAL),
            vectors.readUint(".ballot.outcomeCodes.NIL_TECHNICAL"),
            "NIL_TECHNICAL"
        );
    }

    // ---------------------------------------------------------------------
    // Fuzzed cross-checks
    // ---------------------------------------------------------------------

    /// @dev Fixed-width encoding means two different bids can never share a preimage. A
    /// variable-length scheme would let leafIndex 1 with 23 units collide with leafIndex
    /// 12 with 3 units, which is the class of bug this guards.
    function testFuzz_BidLeafIsInjective(
        uint32 leafIndexA,
        uint32 leafIndexB,
        uint32 unitsA,
        uint32 unitsB,
        bytes32 anchor
    ) public pure {
        vm.assume(leafIndexA != leafIndexB || unitsA != unitsB);

        bytes32 leafA = BallotEncoding.bidLeaf(leafIndexA, bytes16(0), anchor, unitsA, 100_000_000);
        bytes32 leafB = BallotEncoding.bidLeaf(leafIndexB, bytes16(0), anchor, unitsB, 100_000_000);

        assertTrue(leafA != leafB, "two distinct bids produced the same leaf");
    }

    function testFuzz_HashNodeCommutative(bytes32 a, bytes32 b) public pure {
        assertEq(MerkleLib.hashNode(a, b), MerkleLib.hashNode(b, a));
    }

    /// @dev A proof of length one over a two-leaf tree must verify from either side,
    /// which is the base case the fold relies on.
    function testFuzz_TwoLeafTreeVerifiesBothWays(bytes32 leafA, bytes32 leafB) public pure {
        vm.assume(leafA != leafB);
        bytes32 root = MerkleLib.hashNode(leafA, leafB);

        bytes32[] memory proofForA = new bytes32[](1);
        proofForA[0] = leafB;
        assertTrue(MerkleLib.verify(root, leafA, proofForA));

        bytes32[] memory proofForB = new bytes32[](1);
        proofForB[0] = leafA;
        assertTrue(MerkleLib.verify(root, leafB, proofForB));
    }
}
